version: '3.8'

services:
  influxdb:
    image: bitnami/influxdb:1.8.5
    container_name: influxdb
    ports:
      - "8086:8086"
      - "8085:8088"
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=${INFLUXDB_ADMIN_USER_PASSWORD}
      - INFLUXDB_ADMIN_USER_TOKEN=${INFLUXDB_ADMIN_USER_TOKEN}
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=${INFLUXDB_DB}
  granafa:
    image: bitnami/grafana:latest
    ports:
      - "3100:3000"